AWSTemplateFormatVersion: 2010–09–09
Resources:
AWSTemplateFormatVersion: 2010-09-09

Resources:
  LZRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LZCentralAdminRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::924777225109:root
            Action: sts:AssumeRole

  LZRoleRO:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LZCentralReadOnlyRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::924777225109:root
            Action: sts:AssumeRole
            


